INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, YEARS_OF_SERVICE) VALUES ('John', 'Doe', 20);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, YEARS_OF_SERVICE) VALUES ('Debbie', 'Williams', 15);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, YEARS_OF_SERVICE) VALUES ('Joe', 'Jones', 9);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, YEARS_OF_SERVICE) VALUES ('Helen', 'Chan', 5);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, YEARS_OF_SERVICE) VALUES ('John', 'Smith', 12);