DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
  ID INTEGER NOT NULL AUTO_INCREMENT, 
  FIRST_NAME varchar(45), 
  LAST_NAME varchar(45) NOT NULL, 
  YEARS_OF_SERVICE INTEGER, 
  PRIMARY KEY (ID)
);